---
ansible_user: "cisco"
ansible_password: "cisco"
url: "https://{{ ansible_host }}/restconf"

snmp_configure:
  Cisco-IOS-XE-native:snmp-server:
    Cisco-IOS-XE-snmp:community-config:
    - name: thenre
      permission: ro
    Cisco-IOS-XE-snmp:enable:
      enable-choice:
        traps: {}

ntp_configure:
  Cisco-IOS-XE-native:ntp:
    Cisco-IOS-XE-ntp:server:
      server-list:
        - ip-address: 1.1.1.1
          prefer:
            - null
        - ip-address: 8.8.8.8


