---
ospf_configure:
  Cisco-IOS-XE-native:router:
    Cisco-IOS-XE-ospf:router-ospf:
      ospf:
        process-id:
        - id: 1
          network:
          - area: 0
            ip: 3.3.3.3
            wildcard: 0.0.0.0
          - area: 0
            ip: 10.10.11.0
            wildcard: 0.0.0.255
          router-id: 3.3.3.3
